# Generated by Django 4.0.5 on 2022-06-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Ename', models.CharField(max_length=100)),
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
