# Generated by Django 4.0.5 on 2022-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Ename', models.CharField(max_length=100)),
                ('Dname', models.CharField(max_length=100)),
                ('Deptno', models.AutoField(primary_key=True, serialize=False)),
                ('Place', models.CharField(max_length=100)),
            ],
        ),
    ]
