# Generated by Django 4.0.5 on 2022-07-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept2',
            fields=[
                ('Ename', models.CharField(max_length=100)),
                ('Dname', models.CharField(max_length=100)),
                ('Deptno', models.AutoField(primary_key=True, serialize=False)),
                ('Place', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
