# Generated by Django 4.0.5 on 2022-07-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_dept2_delete_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dept2',
        ),
    ]
